### ISSUE TITLE
Potential fix for desktop. Could someone test this please?

### ISSUE THREAD

**Issue by zheroz00** [braden-w/whispering#101]
I had become pretty dependent on the desktop version of this software. I decided to play around in the hosts file to see if redirecting the URL would work, and I think it is. I can be in notepad, trigger the shortcut and speak, and it translates and auto-pastes in notepad. 

Here's what I did.

1. Open the hosts file on Windows. C:\Windows\System32\drivers\etc\ and the file is called 'hosts' with no extension. You will need to open it in a text editor as admin.
2. Add the following lines.

127.0.0.1   chat.openai.com
104.18.32.115   chat.openai.com

3. Save the file.
4. Open a command line as admin and type 'ipconfig /flushdns
5. Profit. (hopefully)

Let me know if this works for anyone. Thanks.

**Comment by swimJim** [comment]
I tried it on the desktop after editing the hosts file in safe mode with administrator privileges. Whenever I try to run the Whisper program, I'm getting an error that says to check my API key still.

**Comment by braden-w** [comment]
Hey guys, sorry for the late response, just wanted to check if I can close this now since Whispering supports pasting on transcription since `v4.0.0` that was PRed in #108.
 
Could you guys verify in the [latest release](https://github.com/braden-w/whispering/releases), and feel free to reopen this thread if you still have issues!
