### ISSUE TITLE
Ads Included in Transcriptions?!

### ISSUE THREAD

**Issue by christopherAI2022** [braden-w/whispering#105]
Uhh... what?

"Go to Beadaholique.com for all of your beading supply needs!"  This was included at the end of my transcription.

Makes me want to buy beads now ANYWHERE other than Beadholique... yikes at this odd invasion.

**Comment by cgbur** [comment]
Was your audio sample odd? If you don’t give it anything it will generate common things in the training data like “thanks for watching!” Perhaps you stumbled into an edge case. However I don’t think this is an issue with this tool but the model from OpenAI

**Comment by doxgt** [comment]
> Uhh... what?
> 
> "Go to Beadaholique.com for all of your beading supply needs!" This was included at the end of my transcription.
> 
> Makes me want to buy beads now ANYWHERE other than Beadholique... yikes at this odd invasion.

I'm afraid not, my friend.  What you encountered was just an example of "hallucination".  It tends to happen at the end of a transcription.  This type of "petit mal" is different from the "grand mal" that's invariably triggered when you feed Whisper a whole file of silence.  I have seen the "petit mal" a handful of times.  I wonder whether it was because I stopped recording a tad too early (in both Whispering, whose hotkeys I remapped in AHK, and my little cURL-based AHK app, I use PTT - releasing the record button too early tends to cut off the ending of a sentence).

No corporate conspiracy here.  Just technological imperfection.

**Comment by braden-w** [comment]
Haha great answer @doxgt , and thank you for resolving the issue!

@christopherAI2022 I tend to also get really weird transcriptions when the script is less than ~5 seconds. It's a weird feature of their API and unfortunately there's not much for us to do except hope that this is the most misaligned technology will be 😅
