### ISSUE TITLE
First recording long delay

### ISSUE THREAD

**Issue by OLH21** [braden-w/whispering#117]
There is a much more long delay at the beginning of the recording than with the previous version . It only happens at the first load  i think .

**Comment by braden-w** [comment]
Hey @OLH21 , thanks for pointing out the issue! I attempted to make this much faster through #127 . Let me know if it is! Hopefully it should be, since I'm parallelizing some of the logic and also not enumerating the media recording devices every time you toggle recording (only if we somehow fail to retrieve the current recording device) This should hopefully lead to a little bit better performance. 

A lot of this is unfortunately still a limitation of how fast the browser can initiate the media stream. If it is still slow, please feel free to reopen this issue and I'll take a look again!
