### ISSUE TITLE
Arc compatibility

### ISSUE THREAD

**Issue by worldoptimizer** [braden-w/whispering#270]
Hello Brandon,

I’m sorry to say that I can no longer use Whispering 4.8.1. It has stopped working in Arc. I can start a recording, but it never returns transcribed; it gets stuck at "Your recording is being transcribed." I am using the latest version of Arc on macOS. Additionally, I am still receiving numerous Arc notifications for every action taken. Clicking on them leads me to an empty tab.

Regards

**Comment by worldoptimizer** [comment]
Invalid value from storage for key "whispering-settings", using default value instead.
((JsonString <-> unknown) <-> (Struct (Encoded side) <-> Struct (Type side))) └─ Type side transformation failure └─ (Struct (Encoded side) <-> Struct (Type side)) └─ Encoded side transformation failure └─ Struct (Encoded side) └─ ["alwaysOnTop"] └─ is missing

**Comment by braden-w** [comment]
Thanks for bringing this to my attention! The web version of Whispering runs automated deploys, which usually is great, but I occasionally have some bugs and need to deploy some hot fixes.

I believe this issue should be fixed in the latest release! See #268 and [this specific commit](https://github.com/braden-w/whispering/pull/268/commits/5cb22e0ccfd0c1fba08a3e1c657935b3f88f5705).

Cheers!
