### ISSUE TITLE
Leading space in pasting transcription.

### ISSUE THREAD

**Issue by quickreactor** [braden-w/whispering#296]
Whispering 5.0 on Windows, the desktop app, when it pastes in the transcription there's a leading space at the front.
 example given in this very comment as i have transcribed each line with whisper.
 In the transcription section of the app it seems to be fine. It must be something to do with the way it's pasted.

**Comment by quickreactor** [comment]
I'm using the groq API if that is relevant.

**Comment by rkhrkh** [comment]
It appears that the leading space issue is **not specific to the Whispering application.** I've tested this with another speech-to-text applications that also uses the Groq API, and encountered the same problem:  

Leading space at the beginning of each transcription.

This consistency across different applications strongly suggests that the issue lies with the Groq API itself rather than with any particular application using it. It seems to be a characteristic of how the API processes and returns transcriptions.

**For developer:** 
This is likely an API-level behavior that you may need to account for in your post-processing of the transcription results.

**For users:** 
The leading space you're experiencing is not a flaw in the Whispering application but rather a quirk of the underlying API used for speech-to-text conversion. You may notice this behavior in other applications that use the same API.

**Comment by quickreactor** [comment]
Thank you for this context! I've reported this as an issue on the Groq website.

**Comment by braden-w** [comment]
Thank you @quickreactor and @rkhrkh ! I use the Groq a lot and also noticed this problem :/ really sorry about that! But what I can do actually is pass a `.trim()` after I get the API response which will automatically truncate whitespace! Shouldn't be too bad, will bundle it into our next release!

**Comment by braden-w** [comment]
Closed in #298! Will be bundled in the next release
