### ISSUE TITLE
 Disable the automatic space at the start of each Groq output.

### ISSUE THREAD

**Issue by swimJim** [braden-w/whispering#315]
I'm using the Groq API and dictating this post right now. Is there some kind of way to disable the automatic space at the start of each input? When there is no space, but the sentences are running together, my spell check takes care of things; it's easy to correct.   In contrast, added spaces are not automatically corrected.  I do believe there was a closed issue about trimming extra spaces when using the Groq API. But as you can see from the start of this output, it began with an unnecessary space before the word, "I'm. "

**Comment by quickreactor** [comment]
Hey, I had a similar issue open here a while back. It's actually fixed in the code, it just hasn't made it to release yet. braden-w added a trim() to the output So if you want to build the app yourself, it will fix this. Otherwise I'm sure a new release is just around the corner.

https://github.com/braden-w/whispering/issues/296

**Comment by rkhrkh** [comment]
I've recently **switched back to the OpenAI API.** 

For personal use, like writing WhatsApp messages or similar things, the spacing at the beginning of the output doesn't bother me at all. 

However, when writing **professional texts,** you constantly have to make corrections because otherwise the text looks unprofessional. Over time, I realized that this disrupts my workflow quite a bit, so for now, I'm back to using the OpenAI API.

**Comment by swimJim** [comment]
> Hey, I had a similar issue open here a while back. It's actually fixed in the code, it just hasn't made it to release yet. braden-w added a trim() to the output So if you want to build the app yourself, it will fix this. Otherwise I'm sure a new release is just around the corner.
> 
> #296

 Thank you for your reply. I did see that there was apparently a fixed issue, but I wasn't sure if it was supposed to be in this current version.  I'm just a goofball who doesn't quite understand how GitHub works. Thanks for bringing the issue up so that it can get fixed in the next version.
