### ISSUE TITLE
App keeps crashing or freezes for a few minutes when I want to access the list of recordings

### ISSUE THREAD

**Issue by rick-urb** [braden-w/whispering#328]
Once its loaded, it works fine. But to initially load the recordings tab always takes very long.

Desktop version, windows 10.

**Comment by braden-w** [comment]
Could you try deleting a few of your past recordings? I'm currently working on #285 and hope to push a fix soon!

The lag is probably the browser attempting to load blob files for many audio files at once (I don't have lazy loading enabled)

An alternative fix could also be to use the dropdown to toggle the audio blob column (so it won't be displayed).

**Comment by rkhrkh** [comment]
I'm experiencing the same freezing issue with the **desktop version on a MacBook M1 Pro** with 16 GB of RAM. On my MacBook, it freezes for only a few seconds, which is still quite annoying.

It's probably because suddenly many records are being loaded. I've already posted a feature request here suggesting that it should be possible to set a specific time period for which records are kept and then automatically deleted. 

**To prevent the freezing phenomenon,** I always go into the recordings when I remember and delete everything manually. As mentioned, it would be desirable if this could happen automatically.

**Comment by rick-urb** [comment]
Okay, yeah, deleting fixed this.

I had 1667 recordings 😅

In that light, once again, THANK YOU, for building this cool app I use constantly, Braden. Especially in respect of your obvious workload at uni. Much appreciated.

I will close this issue, as you are already working on it via #285 .

**Comment by braden-w** [comment]
Aww thank you Rick! Appreciate it :')

And yes, will be making progress this through #285 , thank you @rkhrkh again for the suggestions! Appreciate it a lot.
