### ISSUE TITLE
mac app does not record any sound

### ISSUE THREAD

**Issue by bamboowonder** [braden-w/whispering#52]
Hi there, great app.   We used the chrome extension successfully.   
However the mac dmg doesn't record audio.   I verified that it was given a security exception, and that it has permission to use the microphone.
Tried restarting the app.   Still no sound recorded.
Is there anything further we can do to diagnose this?
Thanks

**Comment by braden-w** [comment]
Hey @bamboowonder , thank you again for bringing this to my attention! Could you double-check that this works and that this still reoccurs with the [latest version](https://github.com/braden-w/whispering/releases)? A lot of pull requests and features have been merged since then.

Hopefully this solves your issue and recording audio is restored.

Feel free to reopen this issue if the issue persists. Thank you once again!
