### ISSUE TITLE
Whispering no longer works for me on Windows 10

### ISSUE THREAD

**Issue by DavidGP** [braden-w/whispering#70]
Unfortunately, Whispering.exe has only been starting with a blank white window for a few days now.

Speech is also no longer converted to text.
The browser extension however works without problems.

Thanks for looking into this issue!

By the way, this app is so terrific that I would gladly donate generously if that is possible.

**Comment by doxgt** [comment]
Take the cURL approach, David, as mentioned here: https://forums.knowbrainer.com/forum/third-party-command-utilities-vocola-unimacro-voicepower-python/3409-openai-s-transcription-api-beginner-level-interaction-and-early-user-experience#post3430.

Knowing you, I have no doubt you'll get something working, with prompting and other bells and whistles, in no time. 

My conclusion is that on Windows, cURL is the path of least resistance.

**Comment by braden-w** [comment]
Sorry @doxgt @DavidGP for jumping on this thread so late—I finally have returned to development a few months later!

@DavidGP Could you verify if this issue still persists in the [latest version](https://github.com/braden-w/whispering/releases) (as of writing, `v4.2.1`)? There have been many changes since earlier this year, so there might be a chance that this issue has been resolved.

If not, please reopen this thread and I'll take a look. Thank you once again!
