### ISSUE TITLE
Why this work only with ChatGPT and not with every input or text?

### ISSUE THREAD

**Issue by jcubic** [braden-w/whispering#86]
This is just common functionality, why only put microphone in ChatGPT prompt and not into every input/textarea and force user to open the extension. Adding the icon will be much simpler and you will not need to create UT at all.

**Comment by OLH21** [comment]
you can still use the keyboard shortcut in every text area ;)

**Comment by braden-w** [comment]
@OLH21 yep! Keyboard shortcut is preferred :)

@jcubic we tried inserting a microphone in every input, and that led to a ton of issues, #118 and #121 as examples.

The issue is that there are way, way more `<input />`, `<textarea />`, and `div` contenteditable elements in a website than one may expect. These inputs are placed in unpredictable locations, and attempting to add a microphone icon to every single one of them ends up breaking most websites.

I really wish that we could insert more microphones, but having tried it myself in the dev and an accidental production builds, it really is not worth it, and you're probably better off using the desktop application!

**Comment by jcubic** [comment]
Sure, but note that this is what Grammarly and LanguageTool are doing. But I understand that you don't want to do this.
