### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by jcubic** [braden-w/whispering#90]
Got this error:

```
whispering:dev: 🔴 ERROR  | No supported UI library found.  You can file an RFC for a new UI Library here: https://github.com/PlasmoHQ/plasmo/issues
```

Running on Fedora GNU/Linux Node.js v20.10.0.

**Comment by Arche151** [comment]
Same issue

**Comment by braden-w** [comment]
Hey guys , thank you again for bringing this to my attention! Could you double-check that this works and that this still reoccurs with the latest version? A lot of pull requests and features have been merged since then. Project was in an incomplete state between releases during April.

Hopefully this solves your issue! Feel free to reopen this issue if the issue persists. Thank you once again!

**Comment by Arche151** [comment]
@braden-w Will be able to try it out later and report back! Thanks for picking up on the development :)

**Comment by braden-w** [comment]
Awesome! Thanks again :)

**Comment by Arche151** [comment]
@braden-w It works now!!, Thank you :))
