### ISSUE TITLE
Recording doesn't start

### ISSUE THREAD

**Issue by CaiCharley** [braden-w/whispering#95]
Hello,

I seem to have an issue with the lastest version as after providing an API key with funds and allowing microphone permissions, no matter what (clicking, space bar, recording hotkeys), the recording never starts (ie doesn't show the red square) and I can't get a transcription. Any ideas on how to troubleshoot this?

**Comment by braden-w** [comment]
Hey @CaiCharley , thank you again for bringing this to my attention! Could you double-check that this works and that this still reoccurs with the [latest version](https://github.com/braden-w/whispering/releases)? A lot of pull requests and features have been merged since then.

Hopefully, the recordings will start after or a notification will let you know what's wrong.

Feel free to reopen this issue if the issue persists. Thank you once again!
