### ISSUE TITLE
Extension doesn't work anymore, due to ChatGPT moving to chatgpt.com from chat.openai.com

### ISSUE THREAD

**Issue by Arche151** [braden-w/whispering#97]
Dear Braden,

could you please quickly fix this?

Kind regards

**Comment by worldoptimizer** [comment]
Yeah, me too. I love this tool. Use it every day.

**Comment by Arche151** [comment]
> Yeah, me too. I love this tool. Use it every day.
[updated_chrome_extension.zip](https://github.com/braden-w/whispering/files/15209714/updated_chrome_extension.zip)

I was able to fix it myself :) I attache the updated Chrome extension.

**Comment by zheroz00** [comment]
> > Yeah, me too. I love this tool. Use it every day.
> > [updated_chrome_extension.zip](https://github.com/braden-w/whispering/files/15209714/updated_chrome_extension.zip)
> 
> I was able to fix it myself :) I attached the updated Chrome extension.

Nice! Would you mind letting us know what you updated? I suppose we would need to wait on the PC app?

**Comment by zheroz00** [comment]
> Yeah, me too. I love this tool. Use it every day.

Same. I rarely type anymore. Feels weird at this point.

**Comment by Arche151** [comment]
> > > Yeah, me too. I love this tool. Use it every day.
> > > [updated_chrome_extension.zip](https://github.com/braden-w/whispering/files/15209714/updated_chrome_extension.zip)
> > 
> > 
> > I was able to fix it myself :) I attached the updated Chrome extension.
> 
> Nice! Would you mind letting us know what you updated? I suppose we would need to wait on the PC app?

I basically just changed the trigger URL :)

**Comment by zheroz00** [comment]
> Author

Hey thanks. Does this work globally as well?

**Comment by OLH21** [comment]
> > Yeah, me too. I love this tool. Use it every day.
> > [updated_chrome_extension.zip](https://github.com/braden-w/whispering/files/15209714/updated_chrome_extension.zip)
> 
> I was able to fix it myself :) I attached the updated Chrome extension.

can you fork it and make a pull request ?

**Comment by AdrienEdoukou** [comment]
Or possibly tell precisely what modifications you made as the dev is apparently not back soon to approve pull requests

**Comment by worldoptimizer** [comment]
This really should be incorporated by OpenAI themselves. I am just realizing how often I used this once it stopped working.

**Comment by OLH21** [comment]
> Or possibly tell precisely what modifications you made as the dev is apparently not back soon to approve pull requests

eventually just the fork, but it's not that easy to install as the validated extension. Better would be @braden-w to make a quick fix and change the base adress and resubmit the extension to google

**Comment by swimJim** [comment]
I successfully side-loaded the extension and entered my newly-generated API key. Also, I allowed the necessary permissions. But the extension does not transcribe my voice when I click record. Has this happened to anyone else?

**Comment by jnance314** [comment]
Ok, so it's clear that this extension isn't being maintained anymore. Sad.

**Comment by cgbur** [comment]
> Ok, so it's clear that this extension isn't being maintained anymore. Sad.

Considering this students side project has been so successful I think is testament to the great work done. Have you considered opening a pull request and contributing the change? Otherwise, I use the desktop version of the app which functions fine for all my computer text input. Give that a try.

**Comment by worldoptimizer** [comment]
Well, I guess the maintainer is just busy. Doing open source myself, I can say it's a matter of having time and passion for these side projects, and it might take a moment to have either again. That said, the upside of Open-Source is you can do it yourself.

You can either use the source in this repo or just use do the following:

1. Install:
https://chromewebstore.google.com/detail/crx-extractordownloader/ajkhmmldknmfjnmeedkbkkojgobmljda?hl=de

2. Navigate to 
https://chromewebstore.google.com/detail/whispering/oilbfihknpdbpfkcncojikmooipnlglo

3. Download it as ZIP using CRX Downloader/Extractor

4. Modify all occurrences of string `chat.openai.com` to `chatgpt.com` across the files (if I recall, mainly the JS-files)

5. Navigate to chrome://extensions/ and disable the non-function one and enable developer mode (top right)

6. Install your modified version by navigating to the modified folder

7. It should work again


Keep the original installed, but deactivate … that way you can return to it once it is updated

**Comment by swimJim** [comment]
> > Ok, so it's clear that this extension isn't being maintained anymore. Sad.
> 
> Considering this students side project has been so successful I think is testament to the great work done. Have you considered opening a pull request and contributing the change? Otherwise, I use the desktop version of the app which functions fine for all my computer text input. Give that a try.

I have not been able to get the desktop version of the app to work since the API changes. How have you managed to do it?

**Comment by doxgt** [comment]
See examples I mentioned here: https://forums.knowbrainer.com/forum/third-party-command-utilities-vocola-unimacro-voicepower-python/3409-openai-s-transcription-api-beginner-level-interaction-and-early-user-experience#post3430

Take it from me (:-)): cURL is the absolute path of least resistance.  A few minutes of reading this: https://developer.zendesk.com/documentation/api-basics/getting-started/installing-and-using-curl/#using-curl-in-windows and the OpenAI API examples are all you need.

The necessity of escaping every double-quote in the inline JSON string with a "/" is a hassle.  But as stated in the zendesk reference, you could upload the JSON string from a file.

Anyway, with cURL and a portable sound recorder such as fmedia/phiola, anyone who has rudimentary familiarity with AutoHotkey can construct their own "Whispering" desktop app in very little time.

The barrier to entry is as low as it gets.  I am speaking from experience.

Then you'd be able to roll with your prompts.  And you should be able to deal with any API changes easily.

Caveat: everything above applies to Windows only, because AHK is Windows only.

**Comment by swimJim** [comment]
Honestly, I was thinking about paying a friendly programmer from freelance website like Fiverr.com to take a look at the source code and put together a downloadable release for the Windows executable desktop version.

**Comment by doxgt** [comment]
Take a look here: 

https://github.com/doxgt/PlayGround/blob/main/Simplest_cURL_GPT_API_Test.ahk

https://github.com/doxgt/PlayGround/blob/main/Elementary_cURL_GPT_API_Test.ahk

I didn't bother integrating the steps of phiola doing recording into my "demonstration files".  But I can tell you it is simple stuff.  

Play with fmedia/phiola.   Got questions, go to AHK forum, they will more than likely trouble-shoot it for you there.  Heck, I could answer your basic questions on how to cobble it further with phiola.  Just that my workflow of using PTT may not be to everyone's liking.  In fact I have to make sure I don't conflict with my existing hotkey setup with Dragon Medical One ...

The meat (which really isn't much) is all in the examples I am posting.

See for yourself how simple cURL turns everything into ... just a bunch of string concatenations, especially for transcribing an audio file with no space in its name/path.  Actually in the simplest examples, you don't even have to concatenate anything.  

The Chat Completion side can be a little tricky due to character escaping and what not.

**Comment by swimJim** [comment]
Rather than doing that, isn't the only thing that needs to be done is replacing all instances that point to chat.openai.com to ChatGPT.com somewhere in the source code for the already existing desktop version?

**Comment by doxgt** [comment]
Totally see what you are saying.

- No point in reinventing the wheel.  The point is to make the wheels that fit my vehicle (better).  Specifically, I need to be able to deploy **prompting**.  Not sure when @braden-w will resume development or would even add prompting.  The only feature in Whispering that I care about is the transcription.  I need more flexible deployment of that.

- I think I might have missed the point of the "ChatGPT" thing, as I was hitherto only using the [HamzaETTH fork](https://github.com/HamzaETTH/whispering), which didn't have "ChatGPT" access on the desktop (or did I miss that, too?) ... I interact with ChatGPT either through the web portal or through API.

- I daresay the average AHKer wouldn't mind the flexibility of interacting with the different OpenAI APIs themself, if available.  With cURL, it is "accessible to the masses".

Cheers!

**Comment by zheroz00** [comment]
I made a post, #101 about a potential desktop fix/workaround. If anyone wouldn't mind trying it out that'd be great. Thanks.

**Comment by doxgt** [comment]
This fork, https://github.com/HamzaETTH/whispering/releases/tag/v3.4.1, has always worked for me since day one when I began to use it. I just tested it now and it is still working fine for desktop dictation. I only have need for desktop dictation and I can't comment on any browser plugin aspects. Sorry.

Since then, I've of course moved on to my CURL-based autohotkey app, which is comparatively very, very simple, and something anyone with a modicum of knowledge in autohotkey can modify with ease.

I can confirm that to really get the most out of Whispering's capability, prompting is essential.

If you are really interested, I think you can take a look at the following two files, one from the original repository here, the other from the above fork:

https://github.com/braden-w/whispering/blob/main/apps/extension/src/lib/transcribeAudioWithWhisperApi.ts

https://github.com/HamzaETTH/whispering/blob/main/apps/web-desktop-app/src/lib/transcribeAudioWithWhisperApi.ts

I could be wrong, but I think in those files, you may be able to add prompts.

Even if you can't tweak prompting "on the go", from perhaps a user-facing input box (which I would be able to with the AHK app, but don't currently), "hard-coded" prompting is still worth having if you wish to do any post-processing to property format punctuations and paragraph marks, etc.

I dictated above through the Autohotkey app, with post-processing of punctuations and paragraph breaks. This was achieved through a combination of regular expressions and prompting.  Nothing hardcore.

**Comment by swimJim** [comment]
> This fork, https://github.com/HamzaETTH/whispering/releases/tag/v3.4.1, has always worked for me since day one when I began to use it. I just tested it now and it is still working fine for desktop dictation. I only have need for desktop dictation and I can't comment on any browser plugin aspects. Sorry.
> 
> Since then, I've of course moved on to my CURL-based autohotkey app, which is comparatively very, very simple, and something anyone with a modicum of knowledge in autohotkey can modify with ease.
> 
> I can confirm that to really get the most out of Whispering's capability, prompting is essential.
> 
> If you are really interested, I think you can take a look at the following two files, one from the original repository here, the other from the above fork:
> 
> https://github.com/braden-w/whispering/blob/main/apps/extension/src/lib/transcribeAudioWithWhisperApi.ts
> 
> https://github.com/HamzaETTH/whispering/blob/main/apps/web-desktop-app/src/lib/transcribeAudioWithWhisperApi.ts
> 
> I could be wrong, but I think in those files, you may be able to add prompts.
> 
> Even if you can't tweak prompting "on the go", from perhaps a user-facing input box (which I would be able to with the AHK app, but don't currently), "hard-coded" prompting is still worth having if you wish to do any post-processing to property format punctuations and paragraph marks, etc.
> 
> I dictated above through the Autohotkey app, with post-processing of punctuations and paragraph breaks. This was achieved through a combination of regular expressions and prompting. Nothing hardcore.
How in the world is that desktop version working for you? I have tried it multiple times on desktop and I keep getting the error to check my API key even though I have generated fresh ones.

**Comment by vmsteiner** [comment]
I can confirm that the desktop version is working for me as well. In fact, I am writing this message using the Whispering desktop app. 
I only started using Whispering a few days ago. Since then I first tried the original version and then replaced it with the fork by HamzaETTH. Both work fine on Windows 10 with my newly generated API key.

**Comment by swimJim** [comment]
Thank you for verifying. As it turns out, I thought I had auto-renew enabled in my billing, but I did not. Now the problem has been fixed.

**Comment by jnance314** [comment]
He closed this issue, but it still doesn't work. The button is no longer added to the input field in chatgpt.

**Comment by OLH21** [comment]
> He closed this issue, but it still doesn't work. The button is no longer added to the input field in chatgpt.

you have to wait for him to put the extension on the google store and the store to approve the extension or you have to build the extension yourself ;)
