### ISSUE TITLE
Chrome Extension - Tailwind Conflicts

### ISSUE THREAD

**Issue by juliankolbe** [braden-w/whispering#99]
How do you avoid having conflicts between your svelte components using tailwindcss and the tailwind that is already present on the chatgpt page for example. This can be somewhat solved using a prefix for tailwind, but I'm noticing that you are not using one, do you simply have no conflicts be coincidence or do you use another method? Cheers!

**Comment by braden-w** [comment]
Hey @juliankolbe , thanks for the question!

I'm using Plasmo's content script UI feature, which injects isolated containers into the document object model that have their own shadow DOM and scoped styling. You can read more about it here:

- [Content Scripts UI – Plasmo](https://docs.plasmo.com/framework/content-scripts-ui)
- [Life Cycle of Plasmo CSUI – Plasmo](https://docs.plasmo.com/framework/content-scripts-ui/life-cycle)
- [Styling Plasmo CSUI – Plasmo](https://docs.plasmo.com/framework/content-scripts-ui/styling)

I've updated the extension and have switched to React because Plasmo, unfortunately, doesn't support Svelte 5, but the principle remains the same.

Cheers!
